### ISSUE TITLE
插屏广告报错

### ISSUE THREAD

**Issue by Clushdada** [gstory0404/quakerbirdad#1]
Debugging will be degraded due to missing types. Rebuilding the project will regenerate the needed module files.
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000103e99e30 Runner`-[QBAdEvent sentEvent:](self=0x0000000283b284b0, _cmd="sentEvent:", arguments=2 key/value pairs) at QBAdEvent.m:31:5
   28  	}
   29  	
   30  	-(void)sentEvent:(NSDictionary*)arguments{
-> 31  	    self.eventSink(arguments);
    	    ^
   32  	}
   33  	
   34  	
Target 0: (Runner) stopped.

**Comment by Clushdada** [comment]
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/52188308/227726302-37643479-7cc1-4475-8fe2-aff5f1247e37.png">
直接闪退

**Comment by gstory0404** [comment]
插件的log日志打印一下 看下是哪一步出现的 @a250059653
