### ISSUE TITLE
升级一下sdk呗

### ISSUE THREAD

**Issue by Clushdada** [gstory0404/quakerbirdad#2]
升级一下sdk呗

**Comment by gstory0404** [comment]
信天翁账号被下了，目前无法使用测试id，可能需要你这边提供下更新包与测试key


| |
Gstory
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月3日 00:39 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | Re: [gstory0404/quakerbirdad] 升级一下sdk呗 (Issue #2) |

Closed #2 as completed.

**Comment by Clushdada** [comment]
> 信天翁账号被下了，目前无法使用测试id，可能需要你这边提供下更新包与测试key | | Gstory的 | | @***.*** |
> [...](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年11月3日 00:39 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> | | 主题 | Re: [gstory0404/quakerbirdad] 升级一下sdk呗 (Issue #2) | Closed #2 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

加我一下QQ3461660286，我这边发给你
